### ISSUE TITLE
`CMake` should not stealthily download dependencies in background

### ISSUE THREAD

**Issue by akallabeth** [KangLin/RabbitCommon#1]
I´ve tried to install this library on my debian machine and encountered a few issues:

1. library naming related as mentioned in https://github.com/KangLin/RabbitRemoteControl/issues/20
2. stuff not already installed on my system is stealthily downloaded from external sources in background and installed
3. trying to install non existing file `share/RabbitCommonTests.sh`

the second thing is something nice to have if explicitly requested, but having a build system download arbitrary code from somewhere is not really something to be endorsed.

**Comment by KangLin** [comment]
Thank you for reviewing.

> stuff not already installed on my system is stealthily downloaded from external sources in background and installed

These libraries are used internally, so they are downloaded from CMAKE for ease of compilation.
